### ISSUE TITLE
Modificar opciones de respuesta en el campo: ESTADO DEL PROYECTO

### ISSUE THREAD

**Issue by DanielaCetares** [umaic/nuevo-sidi#12]
En el campo ESTADO DEL PROYECTO: Quitar las opciones de respuesta:
*Evaluación
*Aprobado

**Comment by yecarrillo** [comment]
Que se debe hacer con los proyectos que actualmente tienen ese estado?

**Comment by DanielaCetares** [comment]
En este momento solo hay uno en en "aprobación", podemos homologarlo con ejecucuión.

**Comment by yecarrillo** [comment]
Se cambiaron los proyectos con estado "Aprobado" a "En ejecución": 
"42528"
"42531"
"42532"
"42539"
"42545"
"42548"
"42550"
Se cambiaron los proyectos con estado "Evaluación" a "En ejecución": 
"42519"
